import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/contexts/userAuthContext";
import { Toaster } from 'react-hot-toast';
import inter from "@/constants/fonts";

export const metadata: Metadata = {
  title: "ICORE - Innovation Club of Ruhuna Engineering",
  keywords: ["ICORE", "Innovation Club of Ruhuna Engineering", "Ruhuna University", "Engineering Club"],
  description: "Generated by ICORE developers",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <AuthProvider>
          <Toaster position="top-right" />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
